% test woid model for different strain parameterisations
% to do:

clear

addpath('../')
addpath('../visualisation')

N = 40;
M = 49;
L = [7.5, 7.5];
dT = 0.035/0.33/16; % baseline timestep, eg rc/v0/8 when bending
saveEvery = 32;
T = 100;

% xyarray = runWoids(T,N,M,L,'bc','noflux','dT',dT,'saveEvery',saveEvery,...
%     'theta_0',pi*37/180);
% save('../results/DA609_noflux')
% animateWoidTrajectories(xyarray,'woid_test_movies/DA609_noflux',L);
% 
% xyarray = runWoids(T,N,M,L,'bc','noflux','dT',dT,'saveEvery',saveEvery,...
%     'theta_0',pi*37/180,'slowingNodes',1:M);
% save('../results/DA609_noflux_slowingNodesAll')
% animateWoidTrajectories(xyarray,'woid_test_movies/DA609_noflux_slowingNodesAll',L);

% eps_LJ = 4e-4;
% rng(1);
% % k_l = 160;
% % k_theta = 80;
% xyarray = runWoids(T,39,M,L,'bc','periodic','dT',dT,'saveEvery',saveEvery,...
%     'theta_0',pi*37/180,'r_LJcutoff',5*0.035,'eps_LJ',eps_LJ,'sigma_LJ',2*0.035...
%     ...%'k_l',k_l,'k_theta',k_theta,...
%     );
% save(['../results/DA609_periodic_lennardjones' num2str(eps_LJ,'%1.0e')...
%     ...%'_kl' num2str(k_l)...
%     ])
% animateWoidTrajectories(xyarray,['woid_test_movies/DA609_periodic_lennardjones' num2str(eps_LJ,'%1.0e')...
%     ...%'_kl' num2str(k_l) '_kTheta' num2str(k_theta)...
%     ],L);

eps_LJ = 4e-4;
k_l = 80;
rng(1);
xyarray = runWoids(T,40,M,L,'bc','periodic','dT',dT,'saveEvery',saveEvery,...
    'revRate',0,'revRateCluster',0,'revRateClusterEdge',0,'Rir',0,... % no reversals
    'Ris',0,'v0',0.15,'vs',0.15... % no slowing down
    ,'r_LJcutoff',5*0.035,'eps_LJ',eps_LJ,'sigma_LJ',2*0.035... % attraction
    ,'k_l',k_l...
    );
save(['../results/dummies_periodic_lennardjones' num2str(eps_LJ,'%1.0e')...
    '_kl' num2str(k_l)...
    '_v' num2str(v0) ...
    ])
animateWoidTrajectories(xyarray,['woid_test_movies/dummies_periodic_lennardjones' num2str(eps_LJ,'%1.0e')...
    '_kl' num2str(k_l)...
    '_v' num2str(v0) ...
    ],L);

% xyarray = runWoids(T,N,M,L,'bc','noflux','dT',dT,'saveEvery',saveEvery,...
%     'v0',0.14,...
%     'omega_m',2*pi*0.26,...
%     'theta_0',pi*37/180,...
%     'revRate',1/11,...
%     'revTime',1.5,...
%     'revRateCluster',1/11,...
%     'headNodes',[],...
%     'tailNodes',[]);
% save('../results/N2_noflux')
% animateWoidTrajectories(xyarray,'woid_test_movies/N2_noflux',L);
